{
  imports = [
    # Configured modules — CLI/TUI tools with declarative settings
    ./atuin.nix
    ./bat.nix
    ./colima.nix
    ./curl.nix
    ./diff-so-fancy.nix
    ./direnv.nix
    ./eza.nix
    ./fzf.nix
    ./ghostty.nix
    ./git.nix
    ./gpg.nix
    ./htop.nix
    ./lf.nix
    ./neovim.nix
    ./procs.nix
    ./ssh.nix
    ./starship.nix
    ./zsh.nix
    ./aliae.nix
    ./broot.nix
    ./btop.nix
    ./carapace.nix
    ./chawan.nix
    ./clock-rs.nix
    ./fastfetch.nix
    ./git-cliff.nix
    ./hstr.nix
    ./jrnl.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./less.nix
    ./mpv.nix
    ./navi.nix
    ./noti.nix
    ./ripgrep.nix
    ./sesh.nix
    ./tealdeer.nix
    ./tmux.nix
    ./yazi.nix
    ./yt-dlp.nix
    ./tz.nix
    ./zk.nix
    ./aria2.nix
    ./difftastic.nix
    ./fd.nix
    ./intelli-shell.nix
    ./jq.nix
    ./man.nix
    ./mc.nix
    ./parallel.nix
    ./pay-respects.nix
    ./radio-active.nix
    ./rclone.nix
    ./readline.nix
    ./script-directory.nix
    ./television.nix
    ./tmate.nix
    ./translate-shell.nix
    ./ttyper.nix
    ./zoxide.nix
    ./awscli.nix
    ./gh.nix
    ./glab.nix
    ./presenterm.nix
    ./runme.nix

    # Active user-data modules — need out-of-Nix setup (permissions, clusters, auth)
    ./aerospace.nix
    ./hammerspoon.nix
    ./karabiner.nix
    ./k9s.nix
    ./kind.nix
    ./sketchybar.nix
    ./notifications.nix
    ./taskwarrior.nix
    ./vscode.nix

    # Stubs — config templates awaiting first activation; see docs/stubs.md
    ./stubs

    # Layered modules — program enabled at system level, settings owned here
    ./aichat.nix
    ./claude-code.nix
    ./fabric-ai.nix
    ./opencode.nix
    ./brave.nix
    ./dbeaver.nix
    ./freetube.nix
    ./joplin-desktop.nix
    ./obsidian.nix
    ./sioyek.nix
  ];
}
