# git-cliff: conventional-commits preset for CHANGELOG generation.
# Run `git cliff --unreleased --tag <version>` to preview.
{
  programs.git-cliff.settings = {
    changelog = {
      header = "# Changelog\n\n";
      body = ''
        {% if version %}\
            ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
        {% else %}\
            ## [unreleased]
        {% endif %}\
        {% for group, commits in commits | group_by(attribute="group") %}
            ### {{ group | upper_first }}
            {% for commit in commits %}
                - {% if commit.scope %}*({{ commit.scope }})* {% endif %}{{ commit.message | upper_first }}
            {% endfor %}
        {% endfor %}\n
      '';
      footer = "<!-- generated by git-cliff -->\n";
      trim = true;
    };
    git = {
      conventional_commits = true;
      filter_unconventional = false;
      commit_parsers = [
        {
          message = "^feat";
          group = "Features";
        }
        {
          message = "^fix";
          group = "Bug Fixes";
        }
        {
          message = "^docs";
          group = "Documentation";
        }
        {
          message = "^refactor";
          group = "Refactor";
        }
        {
          message = "^perf";
          group = "Performance";
        }
        {
          message = "^test";
          group = "Tests";
        }
        {
          message = "^chore";
          group = "Chores";
        }
      ];
      filter_commits = false;
      tag_pattern = "v[0-9]*";
      ignore_tags = "";
      topo_order = false;
      sort_commits = "oldest";
    };
  };
}
