name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  flake-check:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Nix flake check
        run: nix flake check --show-trace

      - name: Build Darwin host
        run: nix build .#darwinConfigurations.irfan-personal.system --show-trace
